-- Courses
INSERT INTO COURSE_DETAILS(ID, FULLNAME, CREATED_TIME, LAST_UPDATED_TIME)
VALUES(
        COURSE_ID_SEQ.NEXTVAL,
        'Become A Spider in 50 Steps',
        SYSDATE(),
        SYSDATE()
    );
INSERT INTO COURSE_DETAILS(ID, FULLNAME, CREATED_TIME, LAST_UPDATED_TIME)
VALUES(
        COURSE_ID_SEQ.NEXTVAL,
        'Become A Bat in 100 Steps',
        SYSDATE(),
        SYSDATE()
    );
INSERT INTO COURSE_DETAILS(ID, FULLNAME, CREATED_TIME, LAST_UPDATED_TIME)
VALUES(
        COURSE_ID_SEQ.NEXTVAL,
        'Become A Superman in 200 Steps',
        SYSDATE(),
        SYSDATE()
    );

-- Passports
INSERT INTO PASSPORT(ID, PASSPORT_NUM)
VALUES(PASSPORT_ID_SEQ.NEXTVAL, 'MARVEL_1');
INSERT INTO PASSPORT(ID, PASSPORT_NUM)
VALUES(PASSPORT_ID_SEQ.NEXTVAL, 'DC_1');
INSERT INTO PASSPORT(ID, PASSPORT_NUM)
VALUES(PASSPORT_ID_SEQ.NEXTVAL, 'DC_2');

-- Students
-- Students data must be created after Passport data in order to follow the foreign key restrictions
INSERT INTO STUDENT(ID, FULLNAME, PASSPORT_ID)
VALUES(STUDENT_ID_SEQ.NEXTVAL, 'Peter Parker', 1000);
INSERT INTO STUDENT(ID, FULLNAME, PASSPORT_ID)
VALUES(STUDENT_ID_SEQ.NEXTVAL, 'Bruce Wayne', 1001);
INSERT INTO STUDENT(ID, FULLNAME, PASSPORT_ID)
VALUES(STUDENT_ID_SEQ.NEXTVAL, 'Kal-EI', 1002);

-- Reviews
INSERT INTO REVIEW(ID, RATING, REVIEW_DESC, COURSE_ID)
VALUES(REVIEW_ID_SEQ.NEXTVAL, '4', 'Good!', 1000);
INSERT INTO REVIEW(ID, RATING, REVIEW_DESC, COURSE_ID)
VALUES(REVIEW_ID_SEQ.NEXTVAL, '5', 'Excellent!', 1001);
INSERT INTO REVIEW(ID, RATING, REVIEW_DESC, COURSE_ID)
VALUES(REVIEW_ID_SEQ.NEXTVAL, '3', 'OK...', 1000);