-- Course Data
INSERT INTO COURSE_DETAILS(ID, FULLNAME, CREATED_TIME, LAST_UPDATED_TIME) VALUES(COURSE_ID_SEQ.NEXTVAL, 'Become A Spider in 50 Steps', SYSDATE(), SYSDATE());
INSERT INTO COURSE_DETAILS(ID, FULLNAME, CREATED_TIME, LAST_UPDATED_TIME) VALUES(COURSE_ID_SEQ.NEXTVAL, 'Become A Bat in 100 Steps', SYSDATE(), SYSDATE());
INSERT INTO COURSE_DETAILS(ID, FULLNAME, CREATED_TIME, LAST_UPDATED_TIME) VALUES(COURSE_ID_SEQ.NEXTVAL, 'Become A Superman in 200 Steps', SYSDATE(), SYSDATE());

-- Student Data
INSERT INTO STUDENT(ID, FULLNAME) VALUES(STUDENT_ID_SEQ.NEXTVAL, 'Peter Parker');
INSERT INTO STUDENT(ID, FULLNAME) VALUES(STUDENT_ID_SEQ.NEXTVAL, 'Bruce Wayne');
INSERT INTO STUDENT(ID, FULLNAME) VALUES(STUDENT_ID_SEQ.NEXTVAL, 'Kal-EI');